repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0    # Updated version
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
  - repo: https://github.com/psf/black
    rev: 24.1.1    # Updated version
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0    # Updated version
    hooks:
      - id: flake8